
development:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: pdfDemo_development
  pool: 5
  username: cponcax
  password: bat86

test:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: pdfDemo_test
  pool: 5
  username: cponcax
  password: bat86

production:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: pdfDemo_production
  pool: 5
  username: cponcax
  password: bat86
